name: Free RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
          net user github 123456 /add
          net localgroup administrators github /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
      - name: Get RDP Info
        run: |
          Write-Output "RDP IP: $(hostname -I)"
          Write-Output "Username: github"
          Write-Output "Password: 123456"
